name: CD Workflow - prod

on:
  workflow_dispatch:
#    inputs:
#      image_tag:
#        description: "image tag to deploy on dev server"
#        type: string

jobs:
  deploy:
    name: Deploy Prod Server
    runs-on: ubuntu-latest
    steps:
      - name: Update docker Image # through Bastion Host
        uses: appleboy/ssh-action@master
        with:
          proxy_host: ${{ secrets.BASTION_HOST }}
          proxy_username: ubuntu
          proxy_key: ${{ secrets.BASTION_SSH_KEY }}
          host: ${{ secrets.REMOTE_HOST }}
          username: ubuntu
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: 22
          script: |
            aws ecr get-login-password --region ap-northeast-2 | \
            sudo docker login --username AWS --password-stdin 864493117148.dkr.ecr.ap-northeast-2.amazonaws.com

            export IMAGE_TAG=$(echo "${{ github.ref_name }}" | sed -e "s/refs\/heads\///g" | sed -e "s/\//-/g")

            # replace image tag
            sed -i "s/image: 864493117148.dkr.ecr.ap-northeast-2.amazonaws.com\/nomini-fe\:[a-zA-Z0-9._-]*/image\: 864493117148.dkr.ecr.ap-northeast-2.amazonaws.com\/nomini-fe\:$IMAGE_TAG/" docker-compose.yaml
            sudo docker compose pull nomini-fe
            sudo docker compose up -d nomini-fe1
            sleep 20
            sudo docker compose up -d nomini-fe2
            sudo docker image prune --all --force
